#!/bin/sh
alias ka="killall" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c Magit" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="vifm" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -hNal --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present. \

shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
sv() { vcopy "$(du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf)" ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}

alias aliases="vim $DOTDIR/.config/aliasrc && cp $DOTDIR/.config/aliasrc $HOME/.config/ && source $HOME/.config/aliasrc" \
	amend="git commit --amend" \
	aur="pacaur -S" \
	c="cd" \
	ccat="highlight --out-format=ansi" \
	clip="xclip -sel clipboard" \
	es="vim ~/." \
	gac="git add . && git commit -m" \
	gad="git add --all ." \
	gag="git add . && git commit --amend --no-edit && git push -f" \
	gbc="gdc" \
	gca="git commit -a" \
	gcaa="git commit -a --amend -C HEAD" \
	gcl="git clone" \
	gcm="git commit -m" \
	gc="git commit -v" \
	gco="git checkout" \
	gd="git diff" \
	gdc="git diff --cached" \
	gdm="git diff master" \
	gdt="git difftool" \
	gg="git lg" \
  gl="git log --graph --decorate=auto --pretty=oneline --abbrev-commit" \
	gomdone="git-on-master && gpf && git-done" \
	gp="git push" \
	gpf="git push --force" \
	gph="git push heroku" \
	gpom="git push origin master" \
	gpr="git pull --rebase" \
	gra="git rebase --abort" \
	grc="git rebase --continue" \
	gri="git rebase --interactive" \
	gs="git show" \
	inst="sudo pacman -S" \
	logout="kill -9 -1" \
	ls="ls -hN --color=auto --group-directories-first" \
	m="git checkout master" \
	mastre="master" \
	mutt="neomutt" \
	now="date +%Y-%m-%d.%H:%M:%S" \
	pia="bash $HOME/.pia.sh" \
  qutebrowser="qutebrowser --qt-flag ignore-gpu-blacklist --qt-flag enable-gpu-rasterization --qt-flag enable-native-gpu-memory-buffers --qt-flag num-raster-threads=4" \
	raidstart="mdadm --assemble --scan && mount -a" \
	ranger="ranger && cat /home/tidal/.cache/wal/sequences" \
	reattach="tmux attach" \
	rewal="wal -g -i \"$HOME/Pictures/Wallpapers/vaporwave.jpg\" --saturate 0.75" \
	rm="rm -i" \
	sbox="ssh tidal@hades.feralhosting.com" \
	serv="ssh tidal@tidalpaladin.com" \
	songdl="youtube-dl --extract-audio --audio-format m4a --add-metadata --audio-quality 3 --write-thumbnail --continue" \
	squash="git rebase -i master" \
	svim="sudoedit" \
	susp="systemctl suspend" \
	u="cd ../" \
	update="pacaur -Syu" \
	utdvpn="sudo openconnect vpn.utdallas.edu" \
	vimrc="vim $DOTDIR/.config/nvim/init.vim && cp $DOTDIR/.config/nvim/init.vim $HOME/.config/nvim/" \
	zip="zip -r"
	zshrc="vim $DOTDIR/.zshrc && cp $DOTDIR/.zshrc $HOME/ && source $HOME/.zshrc"

alias -g alg="/mnt/valak/documents/school/CS6363" \
	dotdir="$DOTDIR" \
	G="| grep" \
	L="| less" \
	M="| more" \
	os="/mnt/valak/documents/school/CS5348" \
	xnn="/mnt/valak/documents/school/CS6301"
